[package]
name = "conc"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "1.0.0-alpha.1"
nix = { version = "0.30.1", features = ["ioctl"] }
crossbeam-channel = "0.5.15"
tokio = {  version = "1.45.0", features = ["rt", "rt-multi-thread", "sync"] }
